[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third party tracking (Posthog)
enable_third_party_tracking = false

# Chainlit server address
chainlit_server = ""

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = true
    # List of languages to support
    languages = ["en"]

# Allows users to create task lists
[features.task_list]
    enabled = false

[UI]
# Name of the app and chatbot.
name = "Learning.AI Assistant"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "Your personal AI learning assistant"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = true

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Theme customization
[UI.theme]
light = { mode = "light" }
dark = { mode = "dark" }

# Customize chat settings
[UI.chat]
message_text_size = "16px"
bubble_radius = "12px"
avatar_shape = "circle"

[meta]
generated_by = "0.7.400"
